[versions]
agp = "8.13.1"
appcompat = "1.7.1"
desugar = "2.1.5"
interactivemedia = "3.38.0"
material = "1.13.0"
media3ExoplayerIma = "1.8.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
interactivemedia = { group = "com.google.ads.interactivemedia.v3", name = "interactivemedia", version.ref = "interactivemedia" }
media3-exoplayer-ima = { group = "androidx.media3", name = "media3-exoplayer-ima", version.ref = "media3ExoplayerIma" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

